In [1]:
#1 Initialize an empty array with size 2×2
import numpy as np
empty_array = np.empty((2, 2))
print("Empty array:\n", empty_array)


Empty array:
 [[1.47827726e-315 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


In [2]:
#2 Initialize an all-one array with size 4×2
ones_array = np.ones((4, 2))
print("All-one array:\n", ones_array)


All-one array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
#Return a new array of given shape and type, filled with a fill value
filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("Filled array:\n", filled_array)


Filled array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [5]:
#4. Return a new array of zeros with same shape and type as a given array
original = np.array([[1, 2], [3, 4]], dtype=float)
zeros_like_array = np.zeros_like(original)
print("Zeros like original:\n", zeros_like_array)


Zeros like original:
 [[0. 0.]
 [0. 0.]]


In [6]:
#5 Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(original)
print("Ones like original:\n", ones_like_array)


Ones like original:
 [[1. 1.]
 [1. 1.]]


In [7]:
#6 Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("Converted array:\n", converted_array)


Converted array:
 [1 2 3 4]


In [8]:
#problem 2 Array manipulation with NumPy
#1. Create an array with values ranging from 10 to 49
import numpy as np

array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#2. Create a 3×3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("3x3 matrix from 0 to 8:\n", matrix_0_to_8)


3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#3 Create a 3×3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity matrix:\n", identity_matrix)


3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#4 Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("Mean of random array:\n", mean_value)


Mean of random array:
 0.46194532282928225


In [12]:
#5. Create a 10×10 array with random values and find min and max
random_matrix_10x10 = np.random.random((10, 10))
min_val = random_matrix_10x10.min()
max_val = random_matrix_10x10.max()
print("Min:", min_val, "Max:", max_val)


Min: 0.00809143217568653 Max: 0.9881328476180888


In [13]:
#6 create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("Modified array:\n", zero_array)


Modified array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7 reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)


Reversed array:
 [0 4 0 0 2 1]


In [15]:
#8 create a 2d array with 1 on border and 0 insice
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("Bordered array:\n", border_array)


Bordered array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#9 create and 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard pattern:\n", checkerboard)


Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#PROBLEM 3 : array operations with NumPy
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


In [19]:
#1 add the two arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
add_xy = np.add(x, y)
print("x + y:\n", add_xy)


x + y:
 [[ 6  8]
 [10 13]]


In [20]:
#2 subtract the two arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
sub_xy = np.subtract(x, y)
print("x - y:\n", sub_xy)


x - y:
 [[-4 -4]
 [-4 -3]]


In [21]:
#3 multiply the array with any integer
x = np.array([[1, 2], [3, 5]])
mult_x = x * 3
print("x * 3:\n", mult_x)


x * 3:
 [[ 3  6]
 [ 9 15]]


In [22]:
#4 find the square of each element of the array
x = np.array([[1, 2], [3, 5]])
square_x = np.square(x)
print("Square of x:\n", square_x)


Square of x:
 [[ 1  4]
 [ 9 25]]


In [23]:
#5 dot product between v and w ,x and v , x and y
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
dot_vw = np.dot(v, w)
print("v · w:", dot_vw)
dot_xv = np.dot(x, v)
print("x · v:\n", dot_xv)
dot_xy = np.dot(x, y)
print("x · y:\n", dot_xy)


v · w: 219
x · v:
 [29 77]
x · y:
 [[19 22]
 [50 58]]


In [24]:
#6 concatenate x and y along row ; v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_row)

concat_vw_col = np.vstack((v, w))
print("Concatenate v and w along columns:\n", concat_vw_col)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]


In [25]:
#7 concatenate x and v; observe error
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)
    print("Explanation: x is a 2D array (2x2), v is a 1D array (length 2). Shapes don't match for concatenation along axis 0.")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array (2x2), v is a 1D array (length 2). Shapes don't match for concatenation along axis 0.


In [26]:
#PROBLEM 4.2 HOW FAST IS NumPy
import numpy as np
import time


In [28]:
#1 element - wise addition using python list
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()
result_list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start, "seconds")

#using NumPy Arrays

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start = time.time()
result_array_add = array1 + array2
end = time.time()
print("NumPy array addition time:", end - start, "seconds")


Python list addition time: 0.08068513870239258 seconds
NumPy array addition time: 0.003846406936645508 seconds


In [30]:
#2 element-wise multiplication
#using python lists
start = time.time()
result_list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("Python list multiplication time:", end - start, "seconds")
#using NumPy Arrays
start = time.time()
result_array_mul = array1 * array2
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")



Python list multiplication time: 0.15251946449279785 seconds
NumPy array multiplication time: 0.0023288726806640625 seconds


In [31]:
#3 Dot Product
#using python lists
start = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end = time.time()
print("Python list dot product time:", end - start, "seconds")

#using NumPy arrays
start = time.time()
dot_array = np.dot(array1, array2)
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")



Python list dot product time: 0.09714007377624512 seconds
NumPy array dot product time: 0.0018460750579833984 seconds


In [36]:
#4 Matrix multiplication 1000x1000
#using NumPy lists
np_matrix1 = np.arange(1000000).reshape(1000, 1000)
np_matrix2 = np.arange(1000000).reshape(1000, 1000)

start = time.time()
result_matrix_np = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")




NumPy matrix multiplication time: 2.068998098373413 seconds
